### PR TITLE
Web accessibility

### PR DESCRIPTION
**Pull request by ABDULALI3468**
My website is accessible now to most people. It has good contrast, works with keyboard only also, works correctly with screen reader and many more.

Page titles - no issues found
Image text alternatives - no issues found
Text headings - no issues found
Color contrast - no issues found
Resize - no issues found
Interaction - no issues found
Moving content - no issues found
Multimedia - no issues found
The basic structure of the page - no issues found

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
> My website is accessible now to most people. It has good contrast, works with keyboard only also, works correctly with screen reader and many more.


 Your report should include:
List all points that you have checked, i.e:
- Page titles
- Image text alternatives** (alt text)
- Text headings
- Color contrast
- Resize
- Interaction
- Moving content
- Multimedia
- The basic structure of the page

#### Each point on the list needs to include the result of your evaluation:
If everything was ok, make a statement about that (e.g. "Page titles - no issues found").



- [ ] Kindly add your report   to the description of your pull request, please do this because this is part of the [project requirements 
](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md)

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @ABDULALI3468, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ GitHub flow was correctly used


## Required Changes ♻️
- [ ] Kindly prepare a report listing all points that you have checked, and the result of your evaluation, Check the comment under the review.
_Check the comments under the review._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by sja-thedude — APPROVED** [review]
## Project Approved 👍 

Hi @ABDULALI3468, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

giphy

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ABDULALI3468** [comment]
Well thank you so much. Are you from Pakistan. If yes than we can have some
introduction.

**Pull request closed without merging**
